<?php

namespace App\Http\Controllers;

use App\Models\Card;
use App\Models\User;
use App\Models\UserMessage;
use App\Models\UserVisit;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return response()->json(User::get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return response()->json(User::where('id', $id)->get());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\JsonResponse
     */
    public function edit($id, $name, $email, $bonus, $bonus_pay, $card_pay, $black_list)
    {
        Log::info("bonus_pay  $bonus_pay");
        Log::info("card_pay  $card_pay");

        $bon_pay = 1;

        if ($bonus_pay === "false" || $bonus_pay === "0"|| $bonus_pay === "null") {
            $bon_pay = 0;
        }

        $c_pay = 1;

        if ($card_pay === "false" || $card_pay === "0" || $card_pay === "null") {
            $c_pay = 0;
        }
        $b_list = 1;

        if ($black_list === "false" || $black_list === "0" || $black_list === "null") {
            $b_list = null;
        }
        Log::info("bon_pay  $bon_pay");
        Log::info("c_pay  $c_pay");
        $user = User::find($id);

        $user->name = $name;
        $user->email = $email;
        $user->bonus = $bonus;
        $user->bonus_pay = $bon_pay;
        $user->card_pay = $c_pay;
        $user->black_list = $b_list;
        $user->save();

        return response()->json(User::find($id));
    }

    /**
     * find User from DB
     *
     */
    public function findUser($email)
    {
        $result = ["checkUser" => false];

        $user = User::where("email", $email)->first();
         if ($user) {
             $result = ["checkUser" => true];
         }

        return $result;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }



    public function setForAllPermissionsTrue()
    {
        User::where('id', '>', 0) // Укажите условие, которое выберет все записи (в данном случае, все записи)
        ->update([
            'bonus_pay' => 1,
            'card_pay' => 1,
        ]);

        // Дополнительные действия или возвращение результата, если необходимо
    }


    /**
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();

            $user = User::find($id);

            if (!$user) {
                return response()->json(['error' => 'Пользователь не найден'], 404);
            }

            $user->delete();

            // Удаление сообщений пользователя
            UserMessage::where('user_id', $id)->delete();

            DB::commit();

            return response()->json(['message' => 'Пользователь успешно удален'], 200);
        } catch (\Exception $e) {
            DB::rollBack();

            return response()->json(['error' => 'Произошла ошибка при удалении пользователя'], 500);
        }
    }
    public function destroyEmail($email)
    {
        try {
            DB::beginTransaction();

            $user = User::where("email", $email)->first();

            if (!$user) {
                return response()->json(['error' => 'Пользователь не найден'], 404);
            }
            $cards = Card::where("user_id", $user->id)->delete();
            $user->delete();

            // Удаление сообщений пользователя
            UserMessage::where('user_id', $user->id)->delete();

            DB::commit();

            return response()->json(['message' => 'Пользователь успешно удален'], 200);
        } catch (\Exception $e) {
            DB::rollBack();

            return response()->json(['error' => 'Произошла ошибка при удалении пользователя'], 500);
        }
    }

    public function userPas_2()
    {
        $user_pas_2 = [
            "stephaniareedy.24777@gmail.com",
            "karolynmccorkle.95291@gmail.com",
            "estellepowell.16505@gmail.com",
            "vkolesnik713@gmail.com",
            "hydteamdanger@gmail.com",
            "marjorieflowers.44610@gmail.com",
            "joannaerickson.27704@gmail.com",
            "jenniferreyes.14714@gmail.com",
            "violetthomas.38209@gmail.com",
            "joelstokes.46558@gmail.com",
            "garywallace.39821@gmail.com",
            "joebarnes.85833@gmail.com",
            "heatherchandler.88638@gmail.com",
            "ramonacarpenter.29149@gmail.com",
            "brigettejewell.18489@gmail.com",
            "shainathames.47664@gmail.com",
            "jodyellis.19099@gmail.com",
            "monacooper.08786@gmail.com",
            "martinpearson.50606@gmail.com",
            "angelamorton.61641@gmail.com",
            "henryramirez.64119@gmail.com",
            "rochellecohen.13041@gmail.com",
            "camilleburgess.38267@gmail.com",
            "lenagray.69940@gmail.com",
            "jimmypayne.49749@gmail.com",
            "alyssagraves.24341@gmail.com",
            "irenegomez.64915@gmail.com",
            "alexanderalvarado.62686@gmail.com",
            "sethgutierrez.92770@gmail.com",
            "derekdennis.21914@gmail.com",
            "nicoleandrews.23947@gmail.com",
            "kurtwilkerson.72335@gmail.com",
            "darylnorman.96036@gmail.com",
            "herminacoates.96645@gmail.com",
            "craigmcbride.59479@gmail.com",
            "jeromemiller.66647@gmail.com",
            "jeffreeves.60297@gmail.com",
            "henriettafowler.16397@gmail.com",
            "robertpena.35393@gmail.com",
            "angelmoreno.95688@gmail.com",
            "janellaharrell.93904@gmail.com",
            "lilliambrewster.57657@gmail.com",
            "cecilwebster.53113@gmail.com",
            "clydelarson.96576@gmail.com",
            "angelomaxwell.32157@gmail.com",
            "lionelbecker.85907@gmail.com",
            "abrammccloud.91909@gmail.com",
            "angiesimmons.06843@gmail.com",
            "salvadorgreen.27313@gmail.com",
            "monicareyes7171@gmail.com",
            "darrellpena.00647@gmail.com",
            "jermainestrickland.73478@gmail.com",
            "rogersimpson.73126@gmail.com",
            "lamarsnyder.32005@gmail.com",
            "derekpeters.56489@gmail.com",
            "derrickrodriguez.32515@gmail.com",
            "marionwilkins.84271@gmail.com",
            "daleharper.23105@gmail.com",
            "lamarcarlson.64045@gmail.com",
            "curtisparsons.22651@gmail.com",
            "sofiabogan.62062@gmail.com",
            "lilatran.91985@gmail.com",
            "pcnx439@gmail.com",
            "greggyoung.57206@gmail.com",
            "harrysalazar.76797@gmail.com",
            "jermainesaunders.63930@gmail.com",
            "slyviacornish.99457@gmail.com",
            "lucyfarmer.33344@gmail.com",
            "edmundstrickland.50212@gmail.com",
            "ruthgarrett.26391@gmail.com",
            "vikaboss1990@gmail.com",
            "andrey0936734488@gmail.com",
            "larrythornton.09150@gmail.com",
            "yvettepaul.74040@gmail.com",
            "kristanblank.80638@gmail.com",
            "rickeyroy.20634@gmail.com",
            "shakiraclinton.49973@gmail.com",
            "albertakennedy.67379@gmail.com",
            "whitneygordon.51344@gmail.com",
            "elsiewest.58156@gmail.com",
            "mattreynolds.61771@gmail.com",
            "darrelmorrison.04851@gmail.com",
            "kristachandler.58286@gmail.com",
            "hazelphillips.53954@gmail.com",
            "lesliecooper.36765@gmail.com",
            "arnoldharmon.05781@gmail.com",
            "werereasdrerewuyy@gmail.com",
            "seredaol66@gmail.com",
            "myronallison.34103@gmail.com",
            "jokerjeka4@gmail.com",
            "atutunik66@gmail.com",
            "samoletvovka@gmail.com",
            "playstorecnx0666@gmail.com",
            "cnxplaystore7@gmail.com",
            "dominicklucas.04911@gmail.com",
            "oleksandrkostuk646@gmail.com",
            "sanik2009r@gmail.com",
            "haekyle.94821@gmail.com",
            "balanuhhhkaaa@gmail.com",
            "brilatobrgar@gmail.com",
            "arseniimartin7@gmail.com",
            "pancenkoanna129@gmail.com",
            "mnisenkovalentina@gmail.com",
            "yakuninayana26@gmail.com",
            "mggghhgasd123445@gmail.com",
            "trigubolga33@gmail.com",
            "nestatlststalker@gmail.com",
            "denprorok133005@gmail.com",
            "duaneferguson.04701@gmail.com",
            "alexismorales.26168@gmail.com",
            "stephaniesims.90201@gmail.com",
            "beverlyfloyd.00528@gmail.com",
            "christievega.98066@gmail.com",
            "minimintu6@gmail.com",
            "haekyle.94811@gmail.com",
            "klwave133@gmail.com",
            "guillermogeorge.53120@gmail.com",
            "ericbowers.39777@gmail.com",
            "felixscott.42349@gmail.com",
            "playcnxgpt1@gmail.com",
            "spammy.boracay2022@gmail.com",
            "duanereed.61060@gmail.com",
            "jacquelineclarke.31764@gmail.com",
            "michealgoodwin.49584@gmail.com",
            "beckyhunt.07288@gmail.com",
            "angiehorton.38676@gmail.com",
            "zacharyfitzgerald.31307@gmail.com",
            "gplaytdkl3@gmail.com",
            "jermainewarren.27895@gmail.com",
            "tdblr41@gmail.com",
            "billiconaway.07178@gmail.com",
            "coryweber.95014@gmail.com",
            "angiehorton.30219@gmail.com",
            "alfredowade.55658@gmail.com",
            "yolandagregory.65060@gmail.com",
            "matthewcasey.19008@gmail.com",
            "danaguerrero.97625@gmail.com",
            "damonwheeler.38515@gmail.com",
            "felipechristensen.21852@gmail.com",
            "shizukohoover.43849@gmail.com",
            "bobfields.66156@gmail.com",
            "ramonacarpenter.37365@gmail.com",
            "samueldixon.34576@gmail.com",
            "orlandomaxwell.27459@gmail.com",
            "bangalorewaveb@gmail.com",
            "rogelioholloway.47205@gmail.com",
            "jerryguerrero.44031@gmail.com",
            "kristenhampton.63202@gmail.com",
            "janastevens.09800@gmail.com",
            "cesarbates.04890@gmail.com",
            "sonjalyons.19425@gmail.com",
            "florfusco.58980@gmail.com",
            "bobbybell.33505@gmail.com",
            "cristinarobbins.01225@gmail.com",
            "corypowell.67373@gmail.com",
            "brettmoreno.18435@gmail.com",
            "erikawhite.25038@gmail.com",
            "johnniefernandez.50343@gmail.com",
            "heatherchandler.69409@gmail.com",
            "philnewman.37520@gmail.com",
            "gertrudemalone.72908@gmail.com",
            "nicholeharper.75039@gmail.com",
            "martycarroll.60511@gmail.com",
            "darrelberry.75355@gmail.com",
            "colinbush.81466@gmail.com",
            "coramitchell.67807@gmail.com",
            "bethanylarson.31995@gmail.com",
            "ceciliahuff.36133@gmail.com",
            "karlcohen.91145@gmail.com",
            "larrythornton.07113@gmail.com",
            "joebarnes.23147@gmail.com",
            "phildunn.82510@gmail.com",
            "patsygibson.03724@gmail.com",
            "arturogreen.04167@gmail.com",
            "gplaytdkl2@gmail.com",
            "marionlynch.57925@gmail.com",
            "rosemarybarber.81602@gmail.com",
            "faithglover.01047@gmail.com",
            "cyndysizemore.90410@gmail.com",
            "mamieroberts.89408@gmail.com",
            "tinanorris.98799@gmail.com",
            "daleharper.23079@gmail.com",
            "almagrant.97875@gmail.com",
            "andreluna.49266@gmail.com",
            "jayevans.90914@gmail.com",
            "rosemarybarber.04191@gmail.com",
            "alfredweaver.05120@gmail.com",
            "estellepowell.16396@gmail.com",
            "everettedwards.66816@gmail.com",
            "sophiawalton.16557@gmail.com",
            "jeromemiller.66589@gmail.com",
            "gilbertogreer.57011@gmail.com",
            "cnxplaystore4@gmail.com",
            "playstorecnx130@gmail.com",
            "bennywilliams.03279@gmail.com",
            "lolapadilla.01643@gmail.com",
            "berniceowen.66960@gmail.com",
            "keithbush.68185@gmail.com",
            "cnx1207@gmail.com",
            "theresaterry.55497@gmail.com",
            "harrysalazar.98218@gmail.com",
            "elgoogclass15@gmail.com",
            "myragreene.63761@gmail.com",
            "kennysteele.04664@gmail.com",
            "mariovargas.47622@gmail.com",
            "guillermogeorge.68003@gmail.com",
            "rochellecohen.16710@gmail.com",
            "vaughnwerner.98208@gmail.com",
            "samueldixon.44160@gmail.com",
            "philnewman.37519@gmail.com",
            "brettmoreno.18504@gmail.com",
            "cyndysizemore.90467@gmail.com",
            "amberfernandez.74563@gmail.com",
            "joelstevenson.02364@gmail.com",
            "billiewilkerson.68934@gmail.com",
            "johndeojohndeo75@gmail.com",
            "abrahambanks.45010@gmail.com",
            "doralyons.79430@gmail.com",
            "christiacoyne.14974@gmail.com",
            "gustavolynch.81346@gmail.com",
            "concentrix155@gmail.com",
            "irvingpope.22364@gmail.com",
            "gaylewaters.44406@gmail.com",
            "gradyowen.94116@gmail.com",
            "leonardgarcia.62042@gmail.com",
            "maureenreyes.73314@gmail.com",
            "janispierce.76884@gmail.com",
            "rogersimpson.57103@gmail.com",
            "austinjones.03512@gmail.com",
            "marioncastillo.28348@gmail.com",
            "timweaver.88868@gmail.com",
            "brandonfoster.17492@gmail.com",
            "robertjordan.15275@gmail.com",
            "katrinaflores.73399@gmail.com",
            "terencegregory.33112@gmail.com",
            "rubyflowers.60685@gmail.com",
            "victorwright.10219@gmail.com",
            "greggyoung.57164@gmail.com",
            "gretchenreid.30149@gmail.com",
            "tashashaw.96418@gmail.com",
            "horaceclayton.16031@gmail.com",
            "fatimahgerber.20218@gmail.com",
            "theresagregory.03098@gmail.com",
            "inezlong.43578@gmail.com",
            "adriancook.05265@gmail.com",
            "marthascott.80400@gmail.com",
            "johnlane.16121@gmail.com",
            "dustinwilkerson.44448@gmail.com",
            "joebarnes.87704@gmail.com",
            "armandograham.75548@gmail.com",
            "jennawong.45349@gmail.com",
            "camillepratt.49783@gmail.com",
            "tdglobalwave13@gmail.com",
            "dexterbarker.46649@gmail.com",
            "gilbertogreer.57042@gmail.com",
            "daniellamoriarty.91687@gmail.com",
            "patrickmclaughlin.40957@gmail.com",
            "janethogan.26048@gmail.com",
            "brenthayes.93970@gmail.com",
            "samueldixon.44263@gmail.com",
            "lenadelgado.25154@gmail.com",
            "fatimahgerber.56710@gmail.com",
            "silvialambert.17956@gmail.com",
            "marioleonard.91485@gmail.com",
            "horaceclayton.20607@gmail.com",
            "horaceclayton.20567@gmail.com",
            "dellalynch.41544@gmail.com",
            "natashalarson.83956@gmail.com",
            "rickeybenson.46763@gmail.com",
            "vanessawaters.78572@gmail.com",
            "jeremiahallison.77718@gmail.com",
            "agnesbecker.14548@gmail.com",
            "sferaved@gmail.com",
            "henriettafowler.20928@gmail.com",
            "carolhawkins.04371@gmail.com",
            "brandonvaughn.63138@gmail.com",
            "suefowler.64772@gmail.com",
            "loycehays.09111@gmail.com",
            "rogeliostephens.57451@gmail.com",
            "pattywalker.97672@gmail.com",
            "playstorecnx9988@gmail.com",
            "jenniferreyes.14618@gmail.com",
            "mnldevappeals@gmail.com",
            "dellalynch.41559@gmail.com",
            "patsygibson.02941@gmail.com",
            "daisysummers.66202@gmail.com",
            "claypowers.49095@gmail.com",
            "tonyacannon.20027@gmail.com",
            "alanmcdonald.32355@gmail.com",
            "klwave13@gmail.com",
            "shellymckinney.34053@gmail.com",
            "gerardramirez.40570@gmail.com",
            "markharvey.65970@gmail.com",
            "dianaelliott.55956@gmail.com",
            "tdtraining11@gmail.com",
            "bethanylarson.31933@gmail.com",
            "dorisford.20770@gmail.com",
            "repackagingcnx@gmail.com",
            "latoyariley.28287@gmail.com",
            "r567d4vbe5w3h6jqrllbzaos2m-00@cloudtestlabaccounts.com",
            "jessicamckenzie.46107@gmail.com",
            "nicolaswheeler.37865@gmail.com",
            "sethgutierrez.90569@gmail.com",
            "darnellhines.13284@gmail.com",
            "angiehorton.30217@gmail.com",
            "anglatierney.70769@gmail.com",
            "rossaustin.89053@gmail.com",
            "gretchenalexander.85528@gmail.com",
            "angiewelch.97826@gmail.com",
            "takci2012@gmail.com",
            "albertakennedy.67418@gmail.com",
            "raythornton.46543@gmail.com",
            "vaughnwerner.34189@gmail.com",
            "andrey18051@gmail.com",
            "playstorecnx4991@gmail.com",
            "cartaxi4@gmail.com",
            "qsqmfd5b6fpo472vlqmcv6urni-00@cloudtestlabaccounts.com",
        ];
        return $user_pas_2;
    }

    public function userPas_4()
    {
        $user_pas_4 =[
            "doreensimon.89198@gmail.com",
            "uxo6226657@gmail.com",
            "tommywatkins.23565@gmail.com",
            "ronniespencer.16955@gmail.com",
            "daisysummers.84800@gmail.com",
            "brucemorton.08656@gmail.com",
            "duanereed.78178@gmail.com",
            "almabecker.44540@gmail.com",
            "candidabryson.92658@gmail.com",
            "corypowell.67302@gmail.com",
            "gwencook.72074@gmail.com",
            "johannabenson.19847@gmail.com",
            "playc9559@gmail.com",
            "vickycoleman.20723@gmail.com",
            "myronallison.34103@gmail.com",
            "4epyke@gmail.com",
            "vkolesnik713@gmail.com",
            "jermainestrickland.80424@gmail.com",
            "fidelkiev@gmail.com",
            "evgeniysokol1991@gmail.com",
            "tatyananiko2013@gmail.com",
            "naumenkodimka@gmail.com",
            "gajdamakavladimir08@gmail.com",
            "tksystems2010@gmail.com",
            "shakal06021995@gmail.com",
            "vikabudnikov@gmail.com",
            "sergijsinogub29@gmail.com",
            "spantelus73@gmail.com",
            "obendasiuk@gmail.com",
            "german.foton21@gmail.com",
            "vladomelchuk1992@gmail.com",
            "rostislav6059@gmail.com",
            "matthewcruz.63538@gmail.com",
            "billiconaway.95829@gmail.com",
            "rexdaniel.45970@gmail.com",
            "bethanymassey.97322@gmail.com",
            "sferaved@gmail.com",
            "ibulah088@gmail.com",
            "agrodim.com.ua@gmail.com",
            "gosha.pushckar@gmail.com",
            "shynkarenko.viktor82@gmail.com",
            "dmitryvarshani@gmail.com",
            "aspirantsp@gmail.com",
            "btldepartment@gmail.com",
            "gpt1mnl2022@gmail.com",
            "vetushkoy@gmail.com",
            "polliks1993@gmail.com",
            "vishchiy@gmail.com",
            "ramm123stein123@gmail.com",
            "kolan030596@gmail.com",
            "romeoomister@gmail.com",
            "m46535516@gmail.com",
            "gsevcuk40@gmail.com",
            "marvells1989z@gmail.com",
            "brathenko1971@gmail.com",
            "tymur.01zh@gmail.com",
            "os8461549@gmail.com",
            "anastasiaploha895@gmail.com",
            "folex18@gmail.com",
            "vidialexnl@gmail.com",
            "svysockiy981@gmail.com",
            "smaksim19820482403@gmail.com",
            "vadospopko@gmail.com",
            "kotovskiviktor20@gmail.com",
            "julianpittman.14789@gmail.com",
            "nodar062@gmail.com",
            "cheefapaypal@gmail.com",
            "rosemarybarber.05101@gmail.com",
            "shainathames.90503@gmail.com",
            "serega1502sh@gmail.com",
            "1notlogin3@gmail.com",
            "zerg61@gmail.com",
            "romancukvovan0704@gmail.com",
            "darylbutler.41165@gmail.com",
            "dimasov70@gmail.com",
            "boriskak55@gmail.com",
            "markboiko2014@gmail.com",
            "stryna1329@gmail.com",
            "andrevoyt82@gmail.com",
            "prestigio114267@gmail.com",
            "ostapetsb@gmail.com",
            "vitalikbugera9@gmail.com",
            "leonidnerukh@gmail.com",
            "skubeenko@gmail.com",
            "tokarchuk565@gmail.com",
            "viktorsergeevmc@gmail.com",
            "laptienkodima1@gmail.com",
            "sovunia03@gmail.com",
            "janicejacobs.37034@gmail.com",
            "andrikju2328@gmail.com",
            "wave23batch3play@gmail.com",
            "artemkotkov99@gmail.com",
            "test1.device123@gmail.com",
            "al200513sda@gmail.com",
            "christievega.76613@gmail.com",
            "curtispearson.53683@gmail.com",
            "wmcastillo.50422@gmail.com",
            "samandrykovalenko@gmail.com",
            "lorihawkins.41281@gmail.com",
            "nedelskijroman@gmail.com",
            "dbarkaster@gmail.com",
            "bmwseruj777@gmail.com",
            "svistyn182@gmail.com",
            "magic27108@gmail.com",
            "zorenkopolina58@gmail.com",
            "zuev.www1985@gmail.com",
            "vaselevskijsasa@gmail.com",
            "mishadidenko964@gmail.com",
            "a0980634997@gmail.com",
            "cvo3980144@gmail.com",
            "v8621945@gmail.com",
            "volodia.wot2020@gmail.com",
            "alexandervasilevych@gmail.com",
            "maximbut06@gmail.com",
            "valera19870101@gmail.com",
            "aveo6885@gmail.com",
            "sdaes171@gmail.com",
            "nata22767@gmail.com",
            "86taran.tino86@gmail.com",
            "grappler16041989@gmail.com",
            "vmakasi52@gmail.com",
            "alx290992@gmail.com",
            "fast.krm@gmail.com",
            "stepanbahcivanzi072@gmail.com",
            "an7002545@gmail.com",
            "fedorova7lyudmila@gmail.com",
            "matrixgpt2@gmail.com",
            "ruthieshort.02626@gmail.com",
            "wwwruhhh@gmail.com",
            "loraphelps.10458@gmail.com",
            "appeals.kl.test@gmail.com",
            "elgoogclass8@gmail.com",
            "elgoogwave14@gmail.com",
            "duanereed.61001@gmail.com",
            "egrushevskii@gmail.com",
            "buravlovevgeniy@gmail.com",
            "fyz4odnbrekmu5cgnxxcjkhlne-01@cloudtestlabaccounts.com",
            "morozoleg014@gmail.com",
            "dmitroivanov99@gmail.com",
            "yusya7007@gmail.com",
            "mail3126888@gmail.com",
            "gmagats@gmail.com",
            "tunko.9889@gmail.com",
            "leytenantdima228@gmail.com",
            "jesusholland.42809@gmail.com",
            "pro100lera@gmail.com",
            "sasha0987137222@gmail.com",
            "ellitokar2192@gmail.com",
            "terizidon123@gmail.com",
            "sergeytatshin@gmail.com",
            "okirilisina@gmail.com",
            "l.arhypchuk@gmail.com",
            "vb0967777@gmail.com",
            "t.a.kolchanova@gmail.com",
            "kam.olga1@gmail.com",
            "fitnesera@gmail.com",
            "tregub.k77@gmail.com",
            "andreyplavan@gmail.com",
            "bocharovaanastasia1992@gmail.com",
            "smilingvovan@gmail.com",
            "evdacevainna@gmail.com",
            "ivancenkoandrej54@gmail.com",
            "aleksey.rudskoy93@gmail.com",
            "vladmirasweet@gmail.com",
            "skrepka76an@gmail.com",
            "alexander040554@gmail.com",
            "artemdimon1969@gmail.com",
            "lemza202@gmail.com",
            "slavadimitrov808@gmail.com",
            "amarozov345@gmail.com",
            "krivrog2@gmail.com",
            "orha802@gmail.com",
            "maks.kutovoy@gmail.com",
            "lesia.kostiv@gmail.com",
            "andreyhudoley83@gmail.com",
            "anna.pobidailo@gmail.com",
            "bilibons1983@i.ua",
            "mozgovojmukola@gmail.com",
            "odegnalov.s.v@gmail.com",
            "05031967a@gmail.com",
            "tolika373@gmail.com",
            "brovarnik1@gmail.com",
            "cfvvfrc32@gmail.com",
            "semenukn28@gmail.com",
            "qariceno@gmail.com",
            "alena0639543507@gmail.com",
            "natalizyrilo@gmail.com",
            "tskurat798@gmail.com",
            "krajzer@gmail.com",
            "ngandzalatatana@gmail.com",
            "anatoliirbnk@gmail.com",
            "sashkokorotenkos@gmail.com",
            "evreyboroda@gmail.com",
            "elenaahmedova7011@gmail.com",
            "svetk92ua@gmail.com",
            "sashahomenok9@gmail.com",
            "britvabarbershopp@gmail.com",
            "yura19beliy98@gmail.com",
            "xunia7@gmail.com",
            "pylypak85@gmail.com",
            "tengiz87@gmail.com",
            "urijgolubenko902@gmail.com",
            "e.gorban1974@gmail.com",
            "sanyaantonov313131@gmail.com",
            "krasnovavalentina79@gmail.com",
            "danuksasa2@gmail.com",
            "ruslan.yasnogor@gmail.com",
            "obynkaya@gmail.com",
            "elena1kornienko1@gmail.com",
            "maxkripak777@gmail.com",
            "lle4ehbka002@gmail.com",
            "felipovich31@gmail.com",
            "shmatoks56@gmail.com",
            "barandichekaterina@gmail.com",
            "asifn0284@gmail.com",
            "moroskaanatolij@gmail.com",
            "lelia.kiss.kyiv@gmail.com",
            "anzelikapavlicenko4@gmail.com",
            "lomovs215@gmail.com",
            "znachkow.andrey08@gmail.com",
            "lukanmiwa82@gmail.com",
            "maks252511@gmail.com",
            "vfelemoncuk@gmail.com",
            "buryachenkoviktor14@gmail.com",
            "sonatanf8718@gmail.com",
            "alizmail77777@gmail.com",
            "k0937887301@gmail.com",
            "svvarenitsa86@gmail.com",
            "v9957424@gmail.com",
            "kolesnik.olena1972@gmail.com",
            "marcosrios.13708@gmail.com",
            "indwave15@gmail.com",
            "amberfernandez.95431@gmail.com",
            "mbk.ivan@gmail.com",
            "ludokmor@gmail.com",
            "kraschenko.natalie@gmail.com",
            "acunskijsergij@gmail.com",
            "v29126728@gmail.com",
            "majskijvladimir@gmail.com",
            "lmkravch2620@gmail.com",
            "olgatarasova121087@gmail.com",
            "timofeevich.a@gmail.com",
            "www.kotik78@gmail.com",
            "mariaiskusnica88@gmail.com",
            "natalikozak9@gmail.com",
            "elgoogstorage1@gmail.com",
            "davidslattery.93826@gmail.com",
            "gon0506nad@gmail.com",
            "svetikkokolya28@gmail.com",
            "jesusholland.42814@gmail.com",
            "genevamarsh.44994@gmail.com",
            "vikkibatista.63352@gmail.com",
            "carychristensen.65647@gmail.com",
            "ebonywalton.34674@gmail.com",
            "gplaytdkl2@gmail.com",
            "mikegeorge.70574@gmail.com",
            "nettiehubbard.10000@gmail.com",
            "keithbush.68152@gmail.com",
            "doretheagaston.91335@gmail.com",
            "rexdaniel.35970@gmail.com",
            "kelleykennedy.11865@gmail.com",
            "wandafreeman.76152@gmail.com",
            "lenadelgado.19644@gmail.com",
            "lindseyboyd.43730@gmail.com",
            "triciamarsh.35175@gmail.com",
            "ramonacastillo.88604@gmail.com",
            "tdglobalwave13@gmail.com",
            "elmerburton.14820@gmail.com",
            "mellisastarr.67215@gmail.com",
            "taylorstanley.99183@gmail.com",
            "alanmcdonald.25238@gmail.com",
            "klwave13@gmail.com",
            "shizukohoover.34003@gmail.com",
            "misyuk.alexandr81@gmail.com",
            "bodo7511445328@gmail.com",
            "olesia.kuznet@gmail.com",
            "angiewelch.97826@gmail.com",
            "blakematthews.38655@gmail.com",
            "fyz4odnbrekmu5cgnxxcjkhlne-00@cloudtestlabaccounts.com",
            "wave482023@gmail.com",
            "doramatthews.98148@gmail.com",
            "kristenhernandez.32968@gmail.com",
            "takci2012@gmail.com",
            "matrixwave19@gmail.com",
            "zay66t5imupink77lkdh3v56yu-00@cloudtestlabaccounts.com",
            "cartaxi4@gmail.com",
            "andrey18051@gmail.com",

        ];
        return $user_pas_4;
    }
    public function userPas_1()
    {
        $user_pas_1 =[
            "vkolesnik713@gmail.com",
            "nmedvedenko11@gmail.com",
            "work.in.taxi@gmail.com",
            "allisonwright.92857@gmail.com",
            "pobeditelbugov@gmail.com",
            "jillrichards.71377@gmail.com",
            "marylucas.59146@gmail.com",
            "cynthiapratt.29708@gmail.com",
            "brandonvaughn.63212@gmail.com",
            "lorenzolawson.37805@gmail.com",
            "cnxplay2023@gmail.com",
            "loreegunther.56608@gmail.com",
            "kelleykennedy.11858@gmail.com",
            "pennyfuller.19609@gmail.com",
            "olgakiuw@gmail.com",
            "shynkarenko.viktor82@gmail.com",
            "black200401@gmail.com",
            "alxbur777@gmail.com",
            "talextalex88888888@gmail.com",
            "caseypatton.33051@gmail.com",
            "dokildom@gmail.com",
            "1notlogin3@gmail.com",
            "svetikkokolya28@gmail.com",
            "vit3862@gmail.com",
            "noemimoser.90619@gmail.com",
            "gingerharmon.95921@gmail.com",
            "ivanitskiy251981@gmail.com",
            "jondahtc@gmail.com",
            "ponomarenko.nataa@gmail.com",
            "katyadzus99@gmail.com",
            "mihailmamyrin@gmail.com",
            "folex18@gmail.com",
            "bondarevzena935@gmail.com",
            "spammy.boracay2022@gmail.com",
            "cyndysizemore.67849@gmail.com",
            "bptrkee@gmail.com",
            "mariyahobotnia@gmail.com",
            "nnumberroonee@gmail.com",
            "alenazakablukovskaya4@gmail.com",
            "voroncovs600@gmail.com",
            "vwm3560@gmail.com",
            "oksanarubanska76@gmail.com",
            "druzuk74@gmail.com",
            "dzavadovroman4@gmail.com",
            "byurii94@gmail.com",
            "katyahodyko@gmail.com",
            "inaacenko359@gmail.com",
            "marionlynch.57940@gmail.com",
            "elenaok551@gmail.com",
            "javierryan.29237@gmail.com",
            "sandrawatson.55388@gmail.com",
            "sheilamurphy.87582@gmail.com",
            "irmarussell.68430@gmail.com",
            "beckyporter.34822@gmail.com",
            "olegfeshenko01@gmail.com",
            "050306mihai@gmail.com",
            "playcnx2023@gmail.com",
            "cnxplay43@gmail.com",
            "beckyporter.34828@gmail.com",
            "raulwallace.61356@gmail.com",
            "majstruklumila@gmail.com",
            "mshftyk2l23uweiuypsyprxcoy-01@cloudtestlabaccounts.com",
            "andrikju2328@gmail.com",
            "tracyjefferson.74405@gmail.com",
            "vladimirkusin80@gmail.com",
            "playstorecnx2910@gmail.com",
            "valerovih19771@gmail.com",
            "sergijstriga@gmail.com",
            "samandrykovalenko@gmail.com",
            "vernajennings.44900@gmail.com",
            "nelsonhawkins.77872@gmail.com",
            "neilhines.43314@gmail.com",
            "olegolfrat1997@gmail.com",
            "rostislavostrovoj@gmail.com",
            "dustik84@gmail.com",
            "frssnuser@gmail.com",
            "sasasuhorenko@gmail.com",
            "lomevgenij304@gmail.com",
            "aoshkalo477@gmail.com",
            "alisaabuhatab@gmail.com",
            "volodimirdobrovolskij5@gmail.com",
            "19flesh91@gmail.com",
            "zmenslusarenko@gmail.com",
            "sergio.chervas@gmail.com",
            "m78577938@gmail.com",
            "gaiduchokyana@gmail.com",
            "nefodovbogdan@gmail.com",
            "txperec@gmail.com",
            "sirokijzeka@gmail.com",
            "dmitrypulyaev@gmail.com",
            "cidvit2578@gmail.com",
            "buravlovevgeniy@gmail.com",
            "alanmcdonald.32368@gmail.com",
            "concentrixdaksh25@gmail.com",
            "elgoogclass8@gmail.com",
            "doramatthews.98148@gmail.com",
            "gosha.pushckar@gmail.com",
            "yuramau12@gmail.com",
            "tvtvttvtattata@gmail.com",
            "prohorenkoandrij@gmail.com",
            "kivitv505@gmail.com",
            "21belik73@gmail.com",
            "maksimdovbis71@gmail.com",
            "lenakassem.lk@gmail.com",
            "mr.vjacheslav93@gmail.com",
            "litvinenkoolena852@gmail.com",
            "dmitropivonis@gmail.com",
            "ellitokar2192@gmail.com",
            "bondarchukyra@gmail.com",
            "sonsenim@gmail.com",
            "olegp9202@gmail.com",
            "tregub.k77@gmail.com",
            "andreyplavan@gmail.com",
            "nastacekan68@gmail.com",
            "konstantinryzhko@gmail.com",
            "peslakvika47@gmail.com",
            "kruz0630@gmail.com",
            "aleksejviderskij7@gmail.com",
            "dim.ivanov971@gmail.com",
            "vadimdzhavakov@gmail.com",
            "umandrina2018@gmail.com",
            "vladuxa193@gmail.com",
            "abilinski@ukr.net",
            "slaveneremeev@gmail.com",
            "dororaisa75@gmail.com",
            "yarem4ukigor6@gmail.com",
            "dima.semenenko.83@gmail.com",
            "nikabucha2016@gmail.com",
            "sashatretyakov1211@gmail.com",
            "kovtoniuk.tanya@gmail.com",
            "yuriikotsiubynskyi@gmail.com",
            "roman.kulikov.kiev@gmail.com",
            "alenakrasnovolska@gmail.com",
            "ssixty808@gmail.com",
            "nina.vlasuk1946@gmail.com",
            "borzakovskaya.e@gmail.com",
            "tel0989319307@gmail.com",
            "cheprasova7771@gmail.com",
            "palanicavolodimir0@gmail.com",
            "tarasova.vika@gmail.com",
            "deniskresan7@gmail.com",
            "8945165werty@gmail.com",
            "vikalina19@gmail.com",
            "marochkanich.sergij@gmail.com",
            "elmarehmedov27@gmail.com",
            "anupiter270471@gmail.com",
            "kornienkogala146@gmail.com",
            "dlyaxvaczkij@gmail.com",
            "o460580@gmail.com",
            "sergeychernyak1975@gmail.com",
            "sergejhomenko003@gmail.com",
            "olgateter5556@gmail.com",
            "veklenko1609@gmail.com",
            "artemskomatin7@gmail.com",
            "ninaryleva2@gmail.com",
            "yulia.schelkina@gmail.com",
            "urijmirosnicenko9@gmail.com",
            "suzannabalasova21@gmail.com",
            "21112011viks@gmail.com",
            "subbotskaamaja@gmail.com",
            "chrolnatasha3@gmail.com",
            "romik17.02.1998@gmail.com",
            "befirsttoday@gmail.com",
            "alena040670@gmail.com",
            "arservisj7@gmail.com",
            "babi4sveta2015@gmail.com",
            "lubovlitovcenko53@gmail.com",
            "natalia.monets88@gmail.com",
            "vera11081940@gmail.com",
            "shumskayaalla@gmail.com",
            "lilu.grebennikova@gmail.com",
            "vip11nagiay@gmail.com",
            "andsomka@gmail.com",
            "ketnait2@gmail.com",
            "grog08082015@gmail.com",
            "deminag123@gmail.com",
            "alexiscarter.00529@gmail.com",
            "marinamirochnik87@gmail.com",
            "nikopss7@gmail.com",
            "oleksandrivnaa54@gmail.com",
            "nidohodukdavid@gmail.com",
            "danilolemesko066@gmail.com",
            "dizel0584@gmail.com",
            "sonadola6@gmail.com",
            "sergii.palamarchuk@gmail.com",
            "sergey.se.5791@gmail.com",
            "vasil.dub2019@gmail.com",
            "rasomaxa0904@gmail.com",
            "vz131517@gmail.com",
            "w7774nk@gmail.com",
            "corzh.sasha2015@gmail.com",
            "anka31880@gmail.com",
            "brujoleg04@gmail.com",
            "aremenkobogdan6@gmail.com",
            "tehnika.17mb@gmail.com",
            "rostislavsmozanik@gmail.com",
            "nadiabogacova8@gmail.com",
            "m08100327@gmail.com",
            "boria.good@gmail.com",
            "takostuk2023@gmail.com",
            "svettta83@gmail.com",
            "lyussi442299@gmail.com",
            "avorskijnazar9@gmail.com",
            "viktorkovalchuk95@gmail.com",
            "irinaarunina264@gmail.com",
            "anatoliirbnk@gmail.com",
            "maksymenkoelena58@gmail.com",
            "valiakovalshuk821@gmail.com",
            "mysikgalina534@gmail.com",
            "idaturner.31835@gmail.com",
            "kruglak96@gmail.com",
            "bg2020vo@gmail.com",
            "deadsoulle@gmail.com",
            "gorelik.nastena@gmail.com",
            "u.milostnaiy@gmail.com",
            "sklyarenkoos85@gmail.com",
            "vadimt849@gmail.com",
            "gerasimenkomariya2007@gmail.com",
            "asevcenkogoncaruk@gmail.com",
            "olesia.kuznet@gmail.com",
            "1986korchovna@gmail.com",
            "ykabakov55@gmail.com",
            "karinalotozka6@gmail.com",
            "oleksandrmelnuhyk31@gmail.com",
            "lesia55555go@gmail.com",
            "bobrovikv777.namber1@gmail.com",
            "vovkakot2121@gmail.com",
            "svitlanalishchuk010275@gmail.com",
            "max.dercach2005@gmail.com",
            "tamilatisenko144@gmail.com",
            "semenuko775@gmail.com",
            "ivanbahilov3@gmail.com",
            "patrickmclaughlin.52371@gmail.com",
            "mkondrateva933@gmail.com",
            "innaogorodnya@gmail.com",
            "bonniegill.77533@gmail.com",
            "iuriistupa@gmail.com",
            "rudnickalarisa814@gmail.com",
            "repackagingcnx@gmail.com",
            "kucherjava_natalija@ukr.net",
            "aleksandrsusidko@gmail.com",
            "shirleetimm.67683@gmail.com",
            "chubukova.valentina@gmail.com",
            "dvdlmop@gmail.com",
            "yaroslav.lopatin8787@gmail.com",
            "kotiknastuha23@gmail.com",
            "aleksandrrodincenko2@gmail.com",
            "matusinsasa94@gmail.com",
            "oleg.onik1972@gmail.com",
            "sergiosipenko22@gmail.com",
            "komarviktor039@gmail.com",
            "a.drojin2@gmail.com",
            "kykakabra@gmail.com",
            "afinagladij@gmail.com",
            "sergiotokarew7@gmail.com",
            "edikcertinkov@gmail.com",
            "elenyska6@gmail.com",
            "vedmidirina96@gmail.com",
            "valeragromacenko@gmail.com",
            "d0560442@gmail.com",
            "lesavincov@gmail.com",
            "ostrovochek017@gmail.com",
            "anatoliy70tania@gmail.com",
            "shulgachkarina0@gmail.com",
            "kostenko199185@gmail.com",
            "grigorijsusta@gmail.com",
            "a85717828@gmail.com",
            "u5826803@gmail.com",
            "stefanushuno71093@gmail.com",
            "nazar25044@gmail.com",
            "kruglakl87@gmail.com",
            "olgab99k@gmail.com",
            "gutsalanna1999@gmail.com",
            "neprostamaria2@gmail.com",
            "serg1004198910@gmail.com",
            "yakudza266@gmail.com",
            "super.hav1535@gmail.com",
            "jivchik0406@gmail.com",
            "gellaxi@gmail.com",
            "sirgejsevcenko831@gmail.com",
            "sirovatkaruslan747@gmail.com",
            "vala31291@gmail.com",
            "ilonka0057@gmail.com",
            "svena30@ukr.net",
            "innakovalenko14.10.2015@gmail.com",
            "semko2297@gmail.com",
            "mihailprivet71@gmail.com",
            "yvelirargona@gmail.com",
            "oleksandr123boris@gmail.com",
            "denusyukalina3@gmail.com",
            "lugovap3@gmail.com",
            "kriwenko1964com@gmail.com",
            "zazirnyy@gmail.com",
            "dmitryizvarin2021@gmail.com",
            "mihnoulia6@gmail.com",
            "sharzevizksenij36@gmail.com",
            "oksanaagodzinska28@gmail.com",
            "rostickmaznichenko@gmail.com",
            "oksanaleon7477@gmail.com",
            "ludmilazaxarova63@gmail.com",
            "smichokmaksim@gmail.com",
            "2583lyudmila@gmail.com",
            "anikeenko.1989@gmail.com",
            "vitaliikolomiets8@gmail.com",
            "fialkamarinec@gmail.com",
            "revenkovanm@gmail.com",
            "svetaletunivskaa@gmail.com",
            "nikteteruk@gmail.com",
            "sasha09914@gmail.com",
            "i85506240@gmail.com",
            "puskar22illa@gmail.com",
            "vasyapupkin010319@gmail.com",
            "ruslanmuzuchenko88@gmail.com",
            "duubosvitlana1992@gmail.com",
            "zenadoimnko@gmail.com",
            "schaslivchik228@gmail.com",
            "dara16062004@gmail.com",
            "kotik8789@gmail.com",
            "amzfd290gx@gmail.com",
            "kuzemailona5679@gmail.com",
            "cristinamahmut@gmail.com",
            "massage8658@gmail.com",
            "victor.kornienko2017@gmail.com",
            "alexxleo@gmail.com",
            "koneculolga@gmail.com",
            "melnikv577@gmail.com",
            "monitoring559@gmail.com",
            "volgogradskayakiev@gmail.com",
            "ulianasviderskaa66@gmail.com",
            "yurcochp1976@gmail.com",
            "0679789506n@gmail.com",
            "rita.pletiana02@gmail.com",
            "zapeskulida@gmail.com",
            "ylia7224@gmail.com",
            "svetakontsevyk@gmail.com",
            "pishchaniy1@gmail.com",
            "kasharik454545@gmail.com",
            "alekseevplaton25@gmail.com",
            "kocuruba43@gmail.com",
            "akremich@gmail.com",
            "sergeysergey2019qw@gmail.com",
            "artur1996arturovia@gmail.com",
            "valievali160@gmail.com",
            "sergeymazda@gmail.com",
            "pilipencko.aniuta30@gmail.com",
            "natakusnir495@gmail.com",
            "tesliuk870@gmail.com",
            "sirykdenis2@gmail.com",
            "ivernigora778@gmail.com",
            "andrey.chepiga@gmail.com",
            "nataliavasilkovska67@gmail.com",
            "glo46256@gmail.com",
            "dadash16061965@gmail.com",
            "ignatvladimir762@gmail.com",
            "revamikola821@gmail.com",
            "vladislavloboda66@gmail.com",
            "marinabalika736@gmail.com",
            "g.denyss525@gmail.com",
            "naumenkozena983@gmail.com",
            "markmoco7@gmail.com",
            "v7341602@gmail.com",
            "ritalysova3@gmail.com",
            "d9502602@gmail.com",
            "tanjatjoma2018@gmail.com",
            "zvyagintsevw@gmail.com",
            "ruslanverestun@gmail.com",
            "epostupnaa@gmail.com",
            "martinsevserg@gmail.com",
            "azuzin956@gmail.com",
            "milevski.dmitriy@gmail.com",
            "vbulah292@gmail.com",
            "zelevaviktoria0@gmail.com",
            "vov25404@gmail.com",
            "elenafadusina387@gmail.com",
            "autofanvp@gmail.com",
            "kovalchukoleksandr662@gmail.com",
            "kovthviktoria@gmail.com",
            "kryhkova050198@gmail.com",
            "horbunov0312@gmail.com",
            "rnvfornet@gmail.com",
            "ttnbuh77@gmail.com",
            "jeniferlo1987@gmail.com",
            "semen1966@gmail.com",
            "johnsmith221079@gmail.com",
            "fomichovalk@gmail.com",
            "vozovdenis1@gmail.com",
            "yamnenkoann@gmail.com",
            "veretilnuk.l.v.2010@gmail.com",
            "balaklavasvl@gmail.com",
            "e2904110@gmail.com",
            "palamartana18@gmail.com",
            "marina29oleksenko@gmail.com",
            "aleksandrmahlin3@gmail.com",
            "teremejcuk@gmail.com",
            "dob-alex@bigmir.net",
            "bars30850448@gmail.com",
            "babijtatana3@gmail.com",
            "lidad0214@gmail.com",
            "mira.shirgan@gmail.com",
            "alinayan1987@gmail.com",
            "tenakovedyard@gmail.com",
            "yliaylia503@gmail.com",
            "gusar7218@gmail.com",
            "sergey.shevjenko84@gmail.com",
            "nikvaz2108@gmail.com",
            "nik.kulish0402@gmail.com",
            "liana123453389@gmail.com",
            "valusausenko9@gmail.com",
            "lilyasukhopar@gmail.com",
            "i86543091@gmail.com",
            "lenagutu69@gmail.com",
            "ruslanbikov9@gmail.com",
            "elenanikolay45@gmail.com",
            "dimamachkov86@gmail.com",
            "tiger.2012.ua@gmail.com",
            "vladsom123456@gmail.com",
            "olhaskibao@gmail.com",
            "boykonata94@gmail.com",
            "rudenko198129@gmail.com",
            "dzimsherikopadze@gmail.com",
            "stroyka55555@gmail.com",
            "tkachenkov195@gmail.com",
            "kolya6195@gmail.com",
            "elena.marchent@gmail.com",
            "kornienkotetana339@gmail.com",
            "alex.1888881@gmail.com",
            "andrey-k10@ukr.net",
            "sergeyshkuyrpela87@gmail.com",
            "ulyanchenko.m@gmail.com",
            "arzamazovatatiana1406@gmail.com",
            "tola06812@gmail.com",
            "muzykasvetlana783@gmail.com",
            "nekrashevskaya1@gmail.com",
            "saha09892@gmail.com",
            "kamcenkosvetlana@gmail.com",
            "l36133849@gmail.com",
            "mariasem1980@gmail.com",
            "aberezij@kamianka1.ukr.education",
            "kapralenkomarina@gmail.com",
            "samka300samka@gmail.com",
            "elenapolyvac@gmail.com",
            "missispersefona@gmail.com",
            "kipnisnataliya28041963@gmail.com",
            "oleg622784@gmail.com",
            "iravolosina7@gmail.com",
            "pereygaartem503@gmail.com",
            "diakiv2002@gmail.com",
            "klipov.vd@gmail.com",
            "kalashnikov05011980@gmail.com",
            "alex.denka2602@gmail.com",
            "v27385038@gmail.com",
            "tanabalic@gmail.com",
            "dunkangorets1987@gmail.com",
            "xlifestudios.pr@gmail.com",
            "dimonvygor55@gmail.com",
            "olenaosadcuk048@gmail.com",
            "bydtanvol19@gmail.com",
            "klymhlib@gmail.com",
            "piotrovicandrij0@gmail.com",
            "marykramar427@gmail.com",
            "zena75482@gmail.com",
            "viktorgula09@gmail.com",
            "kovtunoviczena@gmail.com",
            "dorossenkosergej@gmail.com",
            "mihajlopastusenko66@gmail.com",
            "bukolova.viktoria@gmail.com",
            "drava7g@gmail.com",
            "kulenkoirina39@gmail.com",
            "emezgeka1986@gmail.com",
            "wilfredfleming.61204@gmail.com",
            "mamlajvladimir@gmail.com",
            "ryslanxristenko@gmail.com",
            "jaimejohnston.27303@gmail.com",
            "jeffreeves.77178@gmail.com",
            "karlcohen.91145@gmail.com",
            "kevinuolter@gmail.com",
            "craigmcbride.59405@gmail.com",
            "jeanetterivera.53570@gmail.com",
            "7sveta2008@gmail.com",
            "olegruban565@gmail.com",
            "buskoliza37@gmail.com",
            "yanavodolazska@gmail.com",
            "gretchenmccormick.57619@gmail.com",
            "alexx8434@gmail.com",
            "arustamyan2015@gmail.com",
            "prokopchukruf@gmail.com",
            "rogozin1121@gmail.com",
            "kachyra300788@gmail.com",
            "clintoncollier.58652@gmail.com",
            "vadimlesya88@gmail.com",
            "sykavaleria3014@gmail.com",
            "vmatvijcuk806@gmail.com",
            "zacharyfranklin.21086@gmail.com",
            "nerodavaly1964@gmail.com",
            "zadvornijroman6@gmail.com",
            "11041973mark@gmail.com",
            "cartaxi4@gmail.com",
            "sferaved@gmail.com",
            "savchenko77771@gmail.com",
            "ligunura@gmail.com",
            "1987lex@gmail.com",
            "elainemclaughlin.37988@gmail.com",
            "ronaldinosaska46@gmail.com",
            "nesenuknatala856@gmail.com",
            "rrinavoevoda@gmail.com",
            "andrejandrijcuk329@gmail.com",
            "usmedinskatt@gmail.com",
            "boracaytrainingteamxx@gmail.com",
            "andr4964@gmail.com",
            "mshftyk2l23uweiuypsyprxcoy-00@cloudtestlabaccounts.com",
            "smorldesign@gmail.com",
            "takci2012@gmail.com",
            "andrey18051@gmail.com",
            "45tuhamyfmkmhn4udwk3kc4hsm-00@cloudtestlabaccounts.com",
        ];
        return $user_pas_1;
    }

    public function user_app()
    {
        $users = User::all();
        $user_pas_1 = self::userPas_1(); // Примеры данных в массивах
        $user_pas_4 = self::userPas_4();
        $user_pas_2 = self::userPas_2();
        foreach ($users as $user) {
            $email = $user->email;

            if (in_array($email, $user_pas_1)) {
                $user->app_pas_1 = 1;
                $user->save();
            }

            if (in_array($email, $user_pas_4)) {
                $user->app_pas_4 = 1;
                $user->save();
            }

            if (in_array($email, $user_pas_2)) {
                $user->app_pas_2 = 1;
                $user->save();
            }
        }
    }


    public function userList()
    {
        // Определяем пороговую дату (сегодняшняя дата минус 25 дней)
        $thresholdDate = Carbon::now()->subDays(25);

        // Ищем пользователей, которые не заходили после пороговой даты
        $inactiveUsers = UserVisit::where('created_at', '<=', $thresholdDate)
            ->select('user_id', 'app_name')
            ->distinct()
            ->get();

        // Возвращаем список email
        return User::whereIn('id', $inactiveUsers)
            ->where(function ($query) {
                $query->where('sent_email', '==', 1)
                    ->orWhereNull('sent_email');
            })
            ->select('email', 'app_pas_1', 'app_pas_2', 'app_pas_4')
            ->get();
    }
}
